const assert=require('node:assert/strict'),E=require('../profession-system'),D=require('../profession-data');
const memory=()=>{const map=new Map();return{map,getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v)}};
(async()=>{
 const store=memory();let place={location:'broken-path',accessible:true,activeEncounter:false};const e=E.create({storage:store,context:()=>place});
 assert.equal((await e.gather('vesper-herbs','lantern-wood')).ok,false);assert.equal(store.map.size,0);
 for(let i=0;i<3;i++)assert.equal((await e.gather('vesper-iron-vein')).ok,true);
 const results=await Promise.all([e.craft('forge-iron'),e.craft('forge-iron'),e.craft('forge-iron')]);assert.equal(results.filter(r=>r.ok).length,2);assert.equal(e.state.materials['raw-iron'],0);assert.equal(e.state.materials['forged-iron'],2);assert.equal(e.state.professions.blacksmithing.totalXP,66);assert.equal(e.state.professions.blacksmithing.level,2);
 assert.equal((await e.craft('frontier-brace')).ok,true);assert.equal(e.state.materials['frontier-brace'],1);assert.deepEqual(E.create({storage:store,context:()=>place}).state,e.state);assert.equal(store.map.size,1);
 for(const change of [{...place,accessible:false},{...place,activeEncounter:true},{...place,location:'veyra'}]){place=change;const before=JSON.stringify(e.state);assert.equal((await e.gather('vesper-iron-vein','broken-path')).ok,false);assert.equal(JSON.stringify(e.state),before);}place={location:'vesper-outpost',accessible:true,activeEncounter:false};
 for(let i=0;i<3;i++)await e.gather('vesper-map-scrap');assert.equal((await e.craft('chart-vesper-fragment')).ok,true);for(let i=0;i<3;i++)await e.gather('vesper-map-scrap');const before=e.state;assert.equal((await e.craft('chart-vesper-fragment')).ok,false);assert.deepEqual(e.state,before);
 for(const p of D.professions){const capped=E.growth(p,1e12);assert.equal(capped.level,20);assert.equal(capped.xp,0);assert.ok(capped.totalXP<10000);assert.equal(E.growth(p,E.threshold(1)).level,2)}
 place={location:'lantern-wood',accessible:true};assert.equal((await e.gather('vesper-herbs')).ok,true);assert.equal(e.state.materials['wild-herbs'],2);
 const legacy=E.normalize({version:1,professions:{blacksmithing:{level:2,xp:4}},materials:{'raw-iron':5,evil:99,'wild-herbs':-1},discoveries:['<img>','vesper-fragment-chart','vesper-fragment-chart']});assert.equal(legacy.professions.blacksmithing.totalXP,54);assert.deepEqual(legacy.materials,{'raw-iron':5});assert.deepEqual(legacy.discoveries,['vesper-fragment-chart']);assert.deepEqual(E.normalize(legacy),legacy);const incomplete={...legacy};delete incomplete.version;assert.deepEqual(E.normalize(incomplete),legacy);
 for(const raw of [null,[],{version:1,professions:null,materials:[]},{version:1,professions:{blacksmithing:{level:-2,xp:Infinity}}}])assert.deepEqual(E.normalize(raw),E.empty());
 const cap=E.empty();cap.materials['raw-iron']=E.MAX_MATERIAL;store.setItem(E.KEY,JSON.stringify(cap));place={location:'broken-path',accessible:true};const old=store.getItem(E.KEY);assert.equal((await e.gather('vesper-iron-vein')).ok,false);assert.equal(store.getItem(E.KEY),old);
 cap.materials['raw-iron']=3;cap.materials['forged-iron']=E.MAX_MATERIAL;store.setItem(E.KEY,JSON.stringify(cap));const beforeCraft=store.getItem(E.KEY);assert.equal((await e.craft('forge-iron')).ok,false);assert.equal(store.getItem(E.KEY),beforeCraft);
 store.setItem(E.KEY,'{bad');e.load();assert.equal(e.recovered,true);assert.equal((await e.gather('vesper-iron-vein')).ok,true);
 store.setItem(E.KEY,JSON.stringify({version:99}));assert.equal((await e.gather('vesper-iron-vein')).ok,false);assert.equal(JSON.parse(store.getItem(E.KEY)).version,99);
 for(const broken of [{getItem(){throw Error('read')},setItem(){throw Error('must not write')}},{getItem:()=>null,setItem(){throw Error('quota')}}]){const t=E.create({storage:broken,context:()=>place});assert.equal((await t.gather('vesper-iron-vein')).ok,false);assert.deepEqual(t.state,E.empty());assert.equal(t.storageIssue,true)}
 const q=memory();const seeded=E.empty();seeded.materials['raw-iron']=3;q.setItem(E.KEY,JSON.stringify(seeded));const t=E.create({storage:q,context:()=>place});q.setItem=()=>{throw Error('quota')};assert.equal((await t.craft('forge-iron')).ok,false);assert.deepEqual(t.state,seeded);q.getItem=()=>{throw Error('denied')};assert.equal((await t.craft('forge-iron')).ok,false);assert.deepEqual(t.state,seeded);
 const vm=require('node:vm'),fs=require('node:fs'),sandbox=vm.createContext({window:{addEventListener(){}},ProfessionData:D});Object.defineProperty(sandbox,'localStorage',{get(){throw Error('denied getter')}});vm.runInContext(fs.readFileSync(require.resolve('../profession-system'),'utf8')+'\nglobalThis.issue=ProfessionEngine.create().storageIssue',sandbox);assert.equal(sandbox.issue,true);
 const blocked=E.create({storage:memory(),context:()=>place,exclusive:()=>Promise.reject(Error('lock'))});assert.equal((await blocked.gather('vesper-iron-vein')).ok,false);assert.equal((await E.create({storage:memory()}).gather('vesper-iron-vein','broken-path')).ok,false);
 console.log('PASS M7.3 engine: geography/encounter/access/direct-call guards, queue, costs/output/XP atomicity, insufficient stock, repeated gather/craft/chart, caps, legacy normalization, corruption/future/read/quota, retry and isolated key');
})().catch(e=>{console.error(e);process.exitCode=1});
