const {press}=require('./fixed-navigation-fixture.cjs');
const assert=require('node:assert/strict'),{chromium}=require('playwright');const base=process.env.NYMERIA_TEST_URL||'http://127.0.0.1:8009/nymeria';
(async()=>{const browser=await chromium.launch({executablePath:process.env.NYMERIA_CHROMIUM||'/usr/bin/chromium',args:['--no-sandbox','--no-zygote','--disable-dev-shm-usage','--enable-unsafe-swiftshader']});try{
 for(const width of [320,375,390,430]){
  const c=await browser.newContext({viewport:{width,height:844},isMobile:true,hasTouch:true}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await c.route('**/favicon.ico',r=>r.fulfill({status:204}));await p.addInitScript(()=>window.addEventListener('unhandledrejection',e=>{throw e.reason}));await p.goto(base+'/');
  const other=()=>p.evaluate(()=>JSON.stringify(Object.fromEntries(Object.entries(localStorage).filter(([k])=>k!==ProfessionEngine.KEY))));
  const open=async()=>{await p.locator('#tab-menu').tap();await p.locator('[data-nav="professions"]').tap()};await open();assert.ok(await p.locator('#panel-professions').isVisible());assert.ok(await p.locator('[data-prof-gather="vesper-iron-vein"]').isDisabled());assert.equal((await p.evaluate(()=>ProfessionUI.engine.gather('vesper-iron-vein','broken-path'))).ok,false);
  await p.locator('#navigation-back').tap();assert.ok(await p.locator('#panel-menu').isVisible());await open();assert.match(await p.locator('#profession-root').innerText(),/Raggiungi il luogo/);assert.match(await p.locator('#prof-recipe-forge-iron').innerText(),/Ti mancano: 3 Ferro grezzo/);assert.ok(await p.locator('[data-prof-travel="lantern-wood"]').isDisabled());await p.locator('[data-prof-travel="broken-path"]').tap();await p.waitForFunction(()=>ProgressionStore.state.frontier.location==='broken-path');assert.equal(await p.evaluate(()=>NymeriaNavigation.route.screen),'world');await press(p,'[data-world-profession]');assert.equal(await p.evaluate(()=>NymeriaNavigation.route.screen),'professions');if(width===390)await p.screenshot({path:'/tmp/nymeria-professions-clarity.png',fullPage:true});const snapshot=await other();
  for(let i=0;i<3;i++){await p.locator('[data-prof-gather="vesper-iron-vein"]').tap();await p.waitForFunction(n=>ProfessionUI.engine.state.materials['raw-iron']===n,2*(i+1));assert.match(await p.locator('#profession-status').textContent(),/Raccolti/)}
  for(let i=0;i<2;i++){await p.locator('[data-prof-craft="forge-iron"]').tap();await p.waitForFunction(n=>ProfessionUI.engine.state.materials['forged-iron']===n,i+1)}assert.ok(await p.locator('[data-prof-craft="forge-iron"]').isDisabled());await p.locator('[data-prof-craft="frontier-brace"]').tap();await p.waitForFunction(()=>ProfessionUI.engine.state.materials['frontier-brace']===1);assert.match(await p.locator('#profession-status').textContent(),/Creazione completata/);assert.equal(await other(),snapshot);
  assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.ok((await p.locator('.profession-actions button').evaluateAll(es=>es.map(e=>e.getBoundingClientRect().height))).every(h=>h>=44));
  await p.reload();await open();assert.equal(await p.evaluate(()=>ProfessionUI.engine.state.materials['frontier-brace']),1);await p.locator('#navigation-back').tap();await p.locator('[data-nav="professions"]').tap();assert.equal(await p.evaluate(()=>ProfessionUI.engine.state.professions.blacksmithing.level),2);
  await p.evaluate(()=>{const old=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k===ProfessionEngine.KEY)throw Error('quota');return old.call(this,k,v)}});const before=await p.evaluate(()=>ProfessionUI.engine.state);await p.locator('[data-prof-gather="vesper-iron-vein"]').tap();await p.waitForFunction(()=>ProfessionUI.engine.storageIssue);assert.deepEqual(await p.evaluate(()=>ProfessionUI.engine.state),before);assert.match(await p.locator('#profession-status').textContent(),/non disponibile/);
  assert.deepEqual(errors,[]);await c.close();console.log('PASS M7.3 '+width+'px: Menu/World/Back, gather/craft, feedback, geography, isolated balances, refresh/reopen, quota rollback, touch/overflow/no JS errors');
 }
 // Every existing profession remains usable at its actual unlocked location.
 const mapContext=await browser.newContext({hasTouch:true}),mapPage=await mapContext.newPage();await mapPage.goto(base+'/');assert.equal((await mapPage.evaluate(()=>ProfessionUI.engine.gather('vesper-map-scrap','vesper-outpost'))).ok,false);
 for(const [k,n]of Object.entries(require('../guild-project-data').projects[0].requirements)){const result=await mapPage.evaluate(([k,n])=>GuildProjectSystem.contribute('vesper-watchtower',k,n),[k,n]);assert.equal(result.ok,true)};await mapPage.waitForSelector('#world-update');await mapPage.locator('#world-update button').click();await mapPage.locator('#world-discovered-locations [data-world-enter="vesper-outpost"]').click();await press(mapPage,'[data-world-profession]');
 for(let i=0;i<3;i++){await mapPage.locator('[data-prof-gather="vesper-map-scrap"]').click();await mapPage.waitForFunction(n=>ProfessionUI.engine.state.materials['weathered-map-fragment']===n,i+1)}await mapPage.locator('[data-prof-craft="chart-vesper-fragment"]').click();await mapPage.waitForFunction(()=>ProfessionUI.engine.state.discoveries.includes('vesper-fragment-chart'));assert.ok(await mapPage.locator('[data-prof-craft="chart-vesper-fragment"]').isDisabled());assert.equal((await mapPage.evaluate(()=>ProfessionUI.engine.craft('chart-vesper-fragment'))).ok,false);await mapContext.close();console.log('PASS Vesper Outpost gathering and chart crafting through real World discovery/access');
 const c=await browser.newContext(),a=await c.newPage(),b=await c.newPage();await a.goto(base+'/');await a.evaluate(()=>WorldSystem.enter('broken-path'));await b.goto(base+'/');assert.equal((await a.evaluate(()=>ProfessionUI.engine.gather('vesper-iron-vein'))).ok,true);assert.equal((await b.evaluate(()=>ProfessionUI.engine.gather('vesper-iron-vein'))).ok,false);await b.waitForFunction(()=>ProfessionUI.engine.state.materials['raw-iron']===2);await b.evaluate(()=>WorldSystem.enter('veyra'));assert.equal((await a.evaluate(()=>ProfessionUI.engine.gather('vesper-iron-vein','broken-path'))).ok,false);await b.evaluate(()=>WorldSystem.enter('broken-path'));await a.close();assert.equal((await b.evaluate(()=>ProfessionUI.engine.gather('vesper-iron-vein'))).ok,true);await c.close();console.log('PASS M7.3 two-tab writer, read synchronization and handoff');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
