const navigate = require('./mobile-navigation-fixture.cjs');
/* Actual mobile taps, rendering, cold-load migration and shared-store concurrent claims. */
const assert = require('node:assert/strict');
const dismissNotifications = require('./notifications-fixture.cjs');
const { chromium } = require('playwright');
const base = process.env.NYMERIA_TEST_URL || 'http://127.0.0.1:8000';
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.NYMERIA_CHROMIUM||'/usr/bin/chromium',args:['--no-sandbox']});
 try {
  if (!process.env.NYMERIA_WORLD_DEBUG_ONLY) for(const width of [320,390,430]) for(const cls of ['warden','hunter']) {
   const context=await browser.newContext({viewport:{width,height:844},hasTouch:true,isMobile:true});
   let page=await context.newPage();const errors=[];
   // Use reproducible combat seeds to test progression rather than random encounter luck.
   await page.addInitScript(()=>{Math.random=()=>1/4294967296;});
   const attach=p=>p.on('pageerror',e=>errors.push(e.message));attach(page);
   await page.clock.install({time:new Date('2026-10-06T12:00:00Z')});await page.clock.pauseAt(new Date('2026-10-06T12:00:01Z'));
   await page.goto(base);
   await page.evaluate(cls=>{
    ClassSystem.selectClass(cls);
    const ids=cls==='warden'?{mainHand:'sword',support:'shield',torso:'torso-warden',legs:'legs-sentinel',boots:'boots-plate'}:{mainHand:'bow',support:'quiver',torso:'torso-chain',legs:'legs-chain',boots:'boots-chain'};
    for(const [slot,id] of Object.entries(ids))Equipment.equip(id,slot);
   },cls);
   await navigate(page, 'character');await page.locator('#save').tap();
   await navigate(page, "world");assert.ok(await page.locator('#panel-world').isVisible());
   assert.ok(await page.locator('#world-debug').isHidden());
   assert.equal(await page.locator('#world-zone-name').innerText(),'Frontiera del Vespro');
   await page.locator('[data-world-view="overview"]').tap();assert.ok(await page.locator('[data-world-enter="lantern-wood"]:visible').isDisabled());await page.locator('#navigation-back').tap();
   const tap=async locator=>{await dismissNotifications(page);await locator.tap();await page.waitForFunction(()=>document.getElementById('panel-world').getAttribute('aria-busy')==='false');};
   const accept=id=>tap(page.locator(`#world-location-detail [data-quest-accept="${id}"]`));
   const talk=id=>tap(page.locator(`#world-location-detail [data-world-talk="${id}"]`));
   const enter=async id=>{await tap(page.locator('[data-world-view="overview"]'));await tap(page.locator(`[data-world-enter="${id}"]:visible`));};
   const explore=id=>tap(page.locator(`#world-location-detail [data-world-explore="${id}"]`));
   const claim=async id=>{
    await tap(page.locator('#world-tracked [data-quest-claim="'+id+'"]'));
    assert.equal(await page.evaluate(id=>ProgressionStore.state.frontier.quests[id].status,id),'claimed');
   };
   const fight=async id=>{
    await tap(page.locator(`#world-location-detail [data-world-fight="${id}"]`));
    assert.ok(await page.locator('#world-battle').isVisible());
    assert.equal(await page.locator('#world-resource-name').innerText(),cls==='hunter'?'Concentrazione':'Risolutezza');
    assert.ok(await page.locator('#world-resource-bar').isVisible());
    assert.ok(await page.locator('#world-combat-highlight').isVisible());
    assert.ok(await page.locator('.world-combat-history summary').isVisible());
    assert.ok(await page.locator('#world-resource-bar').getAttribute('aria-valuenow')!==null);
    await page.evaluate(async()=>{WorldUI.engine.advance(180);await WorldUI.settle();});
    const result=await page.evaluate(()=>ProgressionStore.state.frontier.lastEncounter);
    assert.equal(result.outcome,'victory',id);assert.ok(await page.locator('#world-result').isVisible());
    await tap(page.locator('[data-world-continue]'));return result;
   };
   await accept('mq01');await talk('serah');
   await page.reload();await navigate(page, "world");
   assert.equal(await page.evaluate(()=>ProgressionStore.state.frontier.quests.mq01.progress[0]),1);
   assert.ok(await page.locator('#character-creator').isHidden());
   await enter('broken-path');await claim('mq01');await accept('mq02');
   await fight('vesper-raider');
   const active=await page.evaluate(()=>ProgressionStore.state.frontier.quests.mq02);
   assert.deepEqual(active.progress,[1,1]);
   await tap(page.locator('#world-location-detail .world-enemies button[data-world-fight="vesper-raider"]'));
   const ticket=await page.evaluate(()=>ProgressionStore.state.frontier.activeEncounter);
   await page.locator('#world-battle-pause').tap();
   assert.equal(await page.evaluate(()=>WorldUI.engine.status),'paused');
   await page.reload();
   assert.equal(await page.evaluate(()=>ProgressionStore.state.frontier.activeEncounter.id),ticket.id);
   await page.locator('#world-battle-resume').tap();
   await page.evaluate(async()=>{WorldUI.engine.advance(180);await WorldUI.settle();});
   await tap(page.locator('[data-world-continue]'));await fight('vesper-raider');await claim('mq02');
   assert.ok(await page.locator('#world-location-detail [data-world-enter="lantern-wood"]').isEnabled());
   await enter('veyra');await accept('mq03');await enter('lantern-wood');
   await fight('corrupt-hound');await fight('corrupt-hound');await explore('cold-lantern');await fight('twilight-stag');await claim('mq03');
   await enter('elar-ruins');await accept('mq04');await explore('tablet_of_elar');
   assert.match(await page.locator('#world-message').innerText(),/Archeologia 10/);
   await fight('elar-sentinel');await fight('elar-sentinel');await fight('elar-sentinel');await claim('mq04');
   await page.evaluate(()=>Equipment.equip(ProgressionStore.state.frontier.lastQuestClaim.loot[0].itemId,'mainHand'));
   await enter('veyra');await accept('mq05');await enter('vesper-ford');
   assert.ok(await page.locator('[data-world-explore="far-bank"]').isDisabled());
   await fight('ford-reaver');await fight('ford-reaver');await fight('ford-reaver');await fight('ford-commander');await explore('far-bank');await claim('mq05');
   await page.evaluate(()=>Equipment.equip(ProgressionStore.state.frontier.lastQuestClaim.loot[0].itemId,'torso'));
   await enter('veyra');await accept('mq06');await enter('silent-tower');
   // XP fixture for browser speed; engine playthrough levels through real repeatable encounters.
   await page.evaluate(async()=>{await ProgressionStore.transact(s=>{s.totalXP=ProgressionData.thresholds[7];return {ok:true};});});
   await fight('silent-shade');await fight('silence-keeper');await claim('mq06');
   const completed=await page.evaluate(()=>ProgressionStore.state);
   assert.ok(completed.frontier.achievements.includes('frontier-conqueror'));
   const itemId=completed.frontier.lastQuestClaim.loot[0].itemId;
   assert.equal(itemId,cls==='warden'?'silence-plate':'silence-mail');
   const oldXP=completed.totalXP;
   const duplicate=await page.evaluate(()=>QuestSystem.claim('mq06'));assert.equal(duplicate.ok,false);
   assert.equal(await page.evaluate(()=>ProgressionStore.state.totalXP),oldXP);
   await dismissNotifications(page);await page.locator('[data-world-view="journal"]:visible').tap();
   assert.equal(await page.locator('#quest-journal [data-quest-open]').count(),11);
   await page.locator('.journal-entry[data-quest-open="mq06"]').tap();
   assert.match(await page.locator('[data-quest-card="mq06"]').innerText(),/Riscossa/);
   if(width===390 && cls==='hunter')await page.screenshot({path:'/tmp/nymeria-m6-journal-390.png',fullPage:true});
   await navigate(page, 'menu');await page.locator('[data-nav="discoveries"]').tap();
   assert.match(await page.locator('#world-discovery-list').innerText(),/Non decifrata.*Archeologia 10/s);
   assert.match(await page.locator('#world-achievements').innerText(),/Conquistatore della Frontiera/);
   if(width===390 && cls==='hunter')await page.screenshot({path:'/tmp/nymeria-m6-discoveries-390.png',fullPage:true});
   await navigate(page, "inventory");await page.locator(`[data-item-id="${itemId}"]`).tap();
   assert.match(await page.locator('#detail-body').innerText(),/Miglioramento/);
   assert.match(await page.locator('#detail-body').innerText(),/Migliore posseduto/);
   await dismissNotifications(page);
   await page.locator('#close-detail').tap();
   await navigate(page, "character");
   assert.match(await page.locator('#character-xp-label').innerText(),new RegExp(`Livello ${completed.level}`));
   assert.equal(await page.locator('#character-xp-bar').getAttribute('aria-valuenow'),String(completed.currentXP));
   await navigate(page, "expeditions");assert.equal(await page.locator('#expedition-xp-bar').getAttribute('aria-valuenow'),String(completed.currentXP));
   await page.close();page=await context.newPage();attach(page);await page.goto(base);await navigate(page, "world");
   assert.equal(await page.evaluate(()=>ProgressionStore.state.frontier.quests.mq06.status),'claimed');
   assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
   assert.deepEqual(errors,[]);
   console.log(`PASS ${width}px ${cls}: touch full main story, talk/visit/kill/collect/miniboss/boss, pause+refresh/resume, claims/loot/Advisor, XP bars, discovery/title, page reopen, no errors/overflow`);
   await context.close();
  }
  // Cold-load old M5, then actual shared-store concurrent claiming and failure/retry.
  const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true});
  const page=await context.newPage();await page.goto(base+'/?test=1');
  const legacy=await page.evaluate(async()=>{
   ClassSystem.selectClass('warden');ClassSystem.selectBuild('command');Equipment.createCharacter();
   await ProgressionStore.transact(s=>{s.totalXP=637;s.crowns=91;s.materials.ether=7;return {ok:true};});
   const old=ProgressionStore.state;delete old.frontier;localStorage.setItem(ProgressionStorage.KEY,JSON.stringify(old));
   return {old,gear:Equipment.state};
  });
  await page.reload();assert.deepEqual(await page.evaluate(()=>Equipment.state),legacy.gear);
  assert.equal(await page.evaluate(()=>ProgressionStore.state.crowns),91);
  assert.equal(await page.evaluate(()=>ProgressionStore.state.totalXP),637);
  assert.ok(await page.locator('#character-creator').isHidden());
  await navigate(page, 'world');await page.locator('#world-location-detail [data-quest-accept="mq01"]').tap();await navigate(page, 'debug');assert.ok(await page.locator('#world-debug').isVisible());
  const tapDebug=async locator=>{await dismissNotifications(page);await locator.tap();await page.waitForFunction(()=>document.getElementById('panel-world').getAttribute('aria-busy')==='false');};

  await page.locator('#world-debug-quest').selectOption('mq01');
  assert.equal(await page.locator('#world-debug-quest').inputValue(),'mq01');
  await tapDebug(page.locator('[data-quest-debug="reset"]'));
  await page.waitForFunction(()=>ProgressionStore.state.frontier.quests.mq01.status==='active' && ProgressionStore.state.frontier.quests.mq01.progress.every(n=>n===0));
  assert.deepEqual(await page.evaluate(()=>ProgressionStore.state.frontier.quests.mq01.progress),[0,0]);
  await tapDebug(page.locator('[data-quest-debug="complete"]'));
  await page.waitForFunction(()=>ProgressionStore.state.frontier.quests.mq01.status==='completed');
  const claimState=await page.evaluate(()=>{
   const persisted=JSON.parse(localStorage.getItem(ProgressionStorage.KEY));
   return {live:ProgressionStore.state.frontier.quests.mq01.status,saved:persisted?.frontier?.quests?.mq01?.status,xp:ProgressionStore.state.totalXP};
  });
  assert.equal(claimState.live,'completed',JSON.stringify(claimState));
  assert.equal(claimState.saved,'completed',JSON.stringify(claimState));
  const other=await context.newPage();await other.goto(base);
  const otherState=await other.evaluate(()=>ProgressionStore.state.frontier.quests.mq01.status);
  assert.equal(otherState,'completed',JSON.stringify({claimState,otherState}));
  const results=await Promise.all([page.evaluate(()=>QuestSystem.claim('mq01')),other.evaluate(()=>QuestSystem.claim('mq01'))]);
  assert.equal(results.filter(r=>r.ok).length,1,JSON.stringify({claimState,otherState,results}));
  await page.evaluate(()=>ProgressionStore.refresh());
  const claimed=await page.evaluate(()=>({status:ProgressionStore.state.frontier.quests.mq01.status,xp:ProgressionStore.state.totalXP}));
  assert.equal(claimed.status,'claimed',JSON.stringify({claimed,results}));
  assert.equal(claimed.xp,claimState.xp+40,JSON.stringify({claimState,claimed,results}));
  assert.equal(claimed.xp,677);
  await navigate(page, 'debug');await page.locator('#world-debug-location').selectOption('silent-tower');await tapDebug(page.locator('#world-debug-unlock'));
  await tapDebug(page.locator('#world-debug-xp'));assert.equal(await page.evaluate(()=>ProgressionStore.state.totalXP),1177);
  await page.evaluate(()=>{Equipment.equip('sword','mainHand');Equipment.equip('shield','support');});
  await tapDebug(page.locator('#world-debug-boss'));
  await page.waitForFunction(()=>!!ProgressionStore.state.frontier.activeEncounter);
  assert.equal(await page.evaluate(()=>ProgressionStore.state.frontier.activeEncounter.enemyId),'silence-keeper');
  await tapDebug(page.locator('#world-battle-abandon'));
  await page.waitForFunction(()=>!ProgressionStore.state.frontier.activeEncounter);
  await page.evaluate(async()=>{await QuestSystem.accept('sq-debt');await QuestSystem.debug('sq-debt','complete');});
  const xpBeforeFailure=await page.evaluate(()=>ProgressionStore.state.totalXP);
  await page.evaluate(()=>{window.originalWrite=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k===ProgressionStorage.KEY)throw new Error('full');return window.originalWrite.call(this,k,v);};});
  await navigate(page, 'world');await tapDebug(page.locator('#world-tracked [data-quest-claim="sq-debt"]'));
  await page.waitForFunction(()=>document.getElementById('world-storage').textContent.includes('non riuscito'));
  assert.equal(await page.evaluate(()=>ProgressionStore.state.totalXP),xpBeforeFailure);
  assert.equal(await page.evaluate(()=>ProgressionStore.state.frontier.quests['sq-debt'].status),'completed');
  await page.evaluate(()=>{Storage.prototype.setItem=window.originalWrite;});
  await navigate(page, 'world');await tapDebug(page.locator('#world-tracked [data-quest-claim="sq-debt"]'));
  await page.waitForFunction(()=>ProgressionStore.state.frontier.quests['sq-debt'].status==='claimed');
  assert.equal(await page.evaluate(()=>ProgressionStore.state.totalXP),xpBeforeFailure+65);
  await page.goto(base);await navigate(page, "world");assert.ok(await page.locator('#world-debug').isHidden());
  console.log('PASS cold M5 migration + actual two-tab Web Locks claim + DEBUG reset/complete/unlock/XP/boss, failed write/retry, normal UI isolated');
  await context.close();
 } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exit(1)});
